# Generated by Django 4.0.4 on 2022-05-15 22:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rank', models.CharField(choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFC', 'SFC'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT')], max_length=5)),
                ('grade', models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('E6', 'E6'), ('E7', 'E7'), ('O1', 'O1'), ('O2', 'O2'), ('O3', 'O3')], max_length=3)),
                ('pebd', models.DateField(blank=True, null=True)),
                ('date_of_rank', models.DateField(blank=True, null=True)),
                ('expiration_term_of_service', models.DateField(blank=True, null=True)),
                ('section', models.CharField(choices=[('BN STAFF', 'BN STAFF'), ('ALPHA', 'ALPHA'), ('BRAVO', 'BRAVO'), ('CHARLIE', 'CHARLIE'), ('DELTA', 'DELTA'), ('UNASSIGNED', 'UNASSIGNED')], default='UNASSIGNED', max_length=10)),
                ('team', models.CharField(choices=[('HQ', 'HQ'), ('1', '1'), ('2', '2'), ('3', '3'), ('UNASSIGNED', 'UNASSIGNED')], default='UNASSIGNED', max_length=10)),
                ('role', models.CharField(choices=[('BN FSO', 'BN FSO'), ('BN FSNCO', 'BN FSNCO'), ('AFATDS', 'AFATDS'), ('BN FO', 'BN FO'), ('BN RTO', 'BN RTO'), ('CO FSO', 'CO FSO'), ('CO FSNCO', 'CO FSNCO'), ('FO', 'FO'), ('RTO', 'RTO'), ('UNASSIGNED', 'UNASSIGNED')], default='UNASSIGNED', max_length=10)),
                ('acft_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('m4_qual', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('dlc_1_complete', models.BooleanField(blank=True, default=False)),
                ('blc_complete', models.BooleanField(blank=True, default=False)),
                ('dlc_2_complete', models.BooleanField(blank=True, default=False)),
                ('alc_complete', models.BooleanField(blank=True, default=False)),
                ('dlc_3_complete', models.BooleanField(blank=True, default=False)),
                ('slc_complete', models.BooleanField(blank=True, default=False)),
                ('jfo_qualified', models.BooleanField(blank=True, default=False)),
                ('drivers_license', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('PRESENCE', 'PRESENCE'), ('INTELLECT', 'INTELLECT'), ('LEADS', 'LEADS'), ('DEVELOPS', 'DEVELOPS'), ('ACHIEVES', 'ACHIEVES'), ('OVERALL', 'OVERALL')], max_length=10)),
                ('comment_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_coments', to='stms_app.soldier')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldier_comments', to='stms_app.soldier')),
            ],
        ),
    ]
