# Generated by Django 4.0.4 on 2022-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_leader',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
