# Generated by Django 4.0.4 on 2022-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='grade',
            field=models.CharField(blank=True, choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('E6', 'E6'), ('E7', 'E7'), ('O1', 'O1'), ('O2', 'O2'), ('O3', 'O3')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(blank=True, choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFC', 'SFC'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT')], max_length=5, null=True),
        ),
    ]
