# Generated by Django 4.0.4 on 2022-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stms_app', '0002_soldier_is_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='unit_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
